### ISSUE TITLE
Committee voting rules and quorum specification?

### ISSUE THREAD

**Issue by wking** [swcarpentry/board#10]
There are a few references to committee votes in this repository, but no details on what consitutes a vote, other than the “majority vote” phrasing in `governance.md` for reviewing the governance rules (just that file?).  It would be nice to have generic rules for making decisions wherever the committee has jurisdiction.  I propose we explicitly specify that:

* The committee makes decisions by voting at meetings.

And then pick either of the following rules:

* Votes are caried by a majority of those who show up ([following Gentoo][1], but they also allow proxies).  I'd also specify a quorum of five.  So if ≤4 members are present, there can be no votes.  If five are present, it takes three votes to pass.  If six or seven are present, it takes four votes to pass.

* Votes are carried by a majority of members, regardless of attendance.  So it takes four votes to pass regardless of how many members are present.

While we're at it, I'd say that the chair or vice-chair was responsible for calling for the vote, and that the secretary was responsible for recording the results in the minutes.

[1]: http://wiki.gentoo.org/wiki/GLEP:39#Specification

**Comment by wking** [comment]
Hmm, the above rules aren't going to work for subcommittees.  With only seven committee members, is there really a point to formal subcommittees?  How are they supposed to work?  I'd expect that committee members were free to conduct related work or research on their own or in teams of their own choosing, and then present that work at full meetings like all other proposals.  I'd recommend removing all subcommittee phrasing from this repository.

**Comment by wking** [comment]
In response to my confusion about subcommittees in the previous comment, #17, #18, and #19 have clarified their [intended role as brain trusts][1] for committee members in a given subject.  So there is no need for subcommittee-specific voting rules, because subcommittee votes, if they occur, are effectively part of a committee-member's personal descision-making process.  I'd still recommend removing all subcommittee phrasing from `committee-roles.md`, since I don't think we need formal rules about personal descision-making processes.

I'd still like clarity on committee-level voting rules.

[1]: https://github.com/swcarpentry/board/issues/18#issuecomment-77644270

**Comment by katyhuff** [comment]
Hi Trevor. Can you submit a pull request describing your proposed policy in a markdown file? Perhaps call it "process.md"? This will make it easier for the SCF SC to discuss and vote on this concern.

**Comment by wking** [comment]
On Mon, Mar 09, 2015 at 12:30:05PM -0700, Katy Huff wrote:
> Can you submit a pull request describing your proposed policy in a
> markdown file? Perhaps call it "process.md"? This will make it
> easier for the SCF SC to discuss and vote on this concern.

In my initial post I presented a choice between two options:

* Votes are caried by a majority of those who show up…
* Votes are carried by a majority of members, regardless of
  attendance…

There's going to be different wording in each case.  Do we need two
pull requests?  One pull request that has text for both cases, which
we later rebase to leave only the winning case?  Some other method?

It seems easiest to me to have folks vote on these choices before
working up pull requests, but I'm happy to do whatever seems best to
you.  When is the next committee meeting?

**Comment by katyhuff** [comment]
Hi Trevor, as I've noted before, we have been going by Robert's Rules. I
assumed that by suggesting other things, you were requesting we should
deviate from that. I am recommending that you make a proposal if and only
if you want us to deviate from Robert's Rules.

Robert's rules says, in this case, a majority is "more than one half of the
votes cast," which is the former of the two choices you list. It is the
method we're using, as mentioned before. Robert's rules should not be
reproduced in this repository. Only deviations from robert's rules need to
be documented here.

Thus, make a proposal if you want us to deviate from Robert's Rules.
Otherwise, this issue is closed (because it is already documented in
Robert's Rules, global standard for parliamentary procedure).

On Mon, Mar 9, 2015 at 2:30 PM, W. Trevor King <notifications@github.com>
wrote:

> On Mon, Mar 09, 2015 at 12:30:05PM -0700, Katy Huff wrote:
> > Can you submit a pull request describing your proposed policy in a
> > markdown file? Perhaps call it "process.md"? This will make it
> > easier for the SCF SC to discuss and vote on this concern.
>
> In my initial post I presented a choice between two options:
>
> * Votes are caried by a majority of those who show up…
> * Votes are carried by a majority of members, regardless of
> attendance…
>
> There's going to be different wording in each case. Do we need two
> pull requests? One pull request that has text for both cases, which
> we later rebase to leave only the winning case? Some other method?
>
> It seems easiest to me to have folks vote on these choices before
> working up pull requests, but I'm happy to do whatever seems best to
> you. When is the next committee meeting?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swcarpentry/board/issues/10#issuecomment-77947242>.
>



-- 
http://katyhuff.github.com

**Comment by wking** [comment]
On Mon, Mar 09, 2015 at 03:02:21PM -0700, Katy Huff wrote:
> … as I've noted before, we have been going by Robert's Rules.

Sorry, I guess I missed your earlier mention.  I just searched this
repository and swcarpentry/site and couldn't find any matches for
“Robert's Rules”.  Can you point me at the mention?  Or should I
submit a PR naming Robert's Rules and linking to [1,2,3]?

> Robert's rules says, in this case, a majority is "more than one half
> of the votes cast," which is the former of the two choices you list.

Sounds good.  He also defines a quorum as [4]:

  The quorum of any other deliberative assembly with an enrolled
  membership (unless the by-laws provide for a smaller quorum) is a
  majority of all the members.

So that answers my question on that front as well.  The only think I'm
missing is docs applying Robert's Rules to our council.

[1]: http://en.wikipedia.org/wiki/Voting_methods_in_deliberative_assemblies#Voice_votes.2C_rising_votes_.28divisions.29_and_shows_of_hands
[2]: http://en.wikipedia.org/wiki/Robert%27s_Rules_of_Order
[3]: http://www.rulesonline.com/rror-08.htm
[4]: http://www.rulesonline.com/rror-11.htm#64

**Comment by katyhuff** [comment]
You're right @wking . It does look like I never mentioned that to you. I could have sworn I did, but I see you're right. I'll admit, I often formulate draft responses to you and then abandon them because I don't like this semantic back and forth very much. Sorry, that was my mistake.

>  The only think I'm missing is docs applying Robert's Rules to our council.

Don't know what you mean here.

**Comment by wking** [comment]
On Mon, Mar 09, 2015 at 04:06:09PM -0700, W. Trevor King wrote:
> The only think I'm missing is docs applying Robert's Rules to our
> council.

And it looks like he even suggests wording for that [1]:

  Every society, in its by-laws or rules of order, should adopt a rule
  like this: "The rules contained in [specifying the work on
  parliamentary practice] shall govern the society in all cases to
  which they are applicable, and in which they are not inconsistent
  with the by-laws or the special rules of order of this society."
  Without such a rule, any one so disposed can cause great trouble in
  a meeting.

:).  In this case, the work should be “Robert's Rules of Order Newly
Revised, 11th Edition”.  The website I'm quoting from is
rulesonline.com, and I havn't found a clear statement of how it can
legally publish the copyright content of the current rules [2].  I'm
also concerned about having rules that aren't openly accessible.
Maybe it would be better to adopt the 1921 version (e.g. [3])?  Or the
original 1876 version [4]?

[1]: http://www.rulesonline.com/rror-11.htm#67
[2]: http://en.wikipedia.org/wiki/Robert%27s_Rules_of_Order#Other_editions_and_variations
[3]: https://archive.org/details/Robertsrulesofor00robe_201303
[4]: http://www.gutenberg.org/files/9097/9097-8.txt

**Comment by wking** [comment]
On Mon, Mar 09, 2015 at 04:30:03PM -0700, Katy Huff wrote:
> I often formulate draft responses to you and then abandon them
> because I don't like this semantic back and forth very much.

No worries, and I'm fine just leaving these issues to cook until folks
have time to deal with them.  I think it's imporant to resolve them
eventually, but I don't anticipate any problems if they sit quietly
for a few months until we do have time to address them.  I appreciate
you clarifying for me, but I don't want it to feel like I'm pushing
you into something you don't want to do.

**Comment by katyhuff** [comment]
> ... I'm fine just leaving these issues to cook until folks
have time to deal with them.

Thanks!  The Steering Committee does have a lot of somewhat pressing matters to deal with most of the time, so I appreciate your patience.

If you want to add this documentation of Roberts Rules as you've suggested, a pull request  would be great.. As far as which version to use, I suspect the differences between various versions of Roberts Rules are somewhat pedantic in nature. So the procedural difference for us will likely be trivial. If you'd like to suggest your favorite version, we'll trust you. 

Thanks!

**Comment by wking** [comment]
On Mon, Mar 09, 2015 at 04:43:37PM -0700, Katy Huff wrote:
> If you want to add this documentation of Roberts Rules as you've
> suggested, a pull request would be great.

Done in #22.

**Comment by katyhuff** [comment]
Closed with #22. Thank you @wking !
