### ISSUE TITLE
Proxy committee membership

### ISSUE THREAD

**Issue by wking** [swcarpentry/board#11]
Getting seven people together at the same time is hard, so I'd borrow from [Gentoo's rules][1] and say:

* Committee decisions are made by committee members (or their proxies) voting at meetings (with the rest of the rules for voting laid out in #10).
* A proxy must not be an existing committee member, and any single person may not be a proxy for more than one committee member at any given meeting.

I'd leave the proxy-appointment procedure unsaid, since it's easy for council members to contact the other members and share proxy choices.

[1]: http://wiki.gentoo.org/wiki/GLEP:39#Specification

**Comment by katyhuff** [comment]
Hi Trevor. Can you submit a pull request describing your proposed policy in a markdown file? Perhaps call it "proxy-membership.md"? This will make it easier for the SCF SC to discuss and vote on this concern.

**Comment by wking** [comment]
On Mon, Mar 09, 2015 at 12:29:32PM -0700, Katy Huff wrote:
> Can you submit a pull request describing your proposed policy in a
> markdown file? Perhaps call it "proxy-membership.md"?

Done in #23.
