### ISSUE TITLE
Collecting data from instructor discussion sessions

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/board#119]
Based on discussions with Tracy and members of the mentoring subcommittee, we would like to start saving and analyzing the data that we're collecting during instructor discussion sessions. This data can be very useful in figuring out trends in issues that instructors are having, which will help in deciding on actions to help solve those issues. We (myself, assessment specialist and potentially others who are interested) will be qualitatively coding the notes from the discussions on a regular basis (~ monthly), working to fix issues and writing follow-up blog posts.

To collect this data the notes from the discussion sessions need to get copied to a [Google doc](https://docs.google.com/document/d/1zQTkNCev9AzAlA464jUa8ifFaTx_8mb1NX6xvUbaGvM/edit). I've gone through and done this for past discussions, but if the discussion hosts could do this in future, it would save a lot of hassle with Etherpad wrangling.

If someone could add to the procedure-discussion-session.md document the Google doc link above and the instructions - "Please add notes from discussion Etherpad directly to top of document. No need to edit or organize notes. Include any parts of the Etherpad on which you took notes of what the instructors were saying - not just the “Notes” section" - that would be great! 

I'll be sending out an email to the mentoring list shortly. If there is anyone not on the mentoring list who leads discussions, please let me know so I can include them.

**Comment by ErinBecker** [comment]
And please add the date of discussion (and time if more than one discussion that day) to the Google doc.

**Comment by gvwilson** [comment]
Who should this be assigned to?

**Comment by ErinBecker** [comment]
@gvwilson I forgot there was an issue for this. This is already in place. Thanks!
