### ISSUE TITLE
What is the process for community interaction with the SC and DC boards?

### ISSUE THREAD

**Issue by ctb** [swcarpentry/board#141]
With reference to some of the issues raised in #114, and most clearly articulated by @wking in [this comment](https://github.com/swcarpentry/board/issues/114#issuecomment-261094339), I am still wondering:

* How can non-members stay involved in requests submitted to the
  steering or subcommittees?  Should they open swcarpentry/board
  issues/PRs?  Do they have to join the subcommittee?  Do something
  else?

Specifically, once a (sub)community-based discussion has reached the point of specific proposals, (1) how is that issue brought to the attention of the board(s), (2) what is the expected timescale of discussion, and (3) how is feedback or resolution or process communicated from the board back to the specific proposal?

We have a number of potential options in #114 but nothing is very specific and I am left wondering about all three questions.

Given @tracykteal's [comment](https://github.com/swcarpentry/board/issues/114#issuecomment-261410721) that there are *too* many avenues of informal communication it would be nice to pick one avenue for *formal* communication of a well developed issue so that it can be placed in front of the board (a board? both boards?).  This seems particularly important to me given the extraordinary recent growth of the DC and SC committees, the stunning proliferation of committees and web sites and personnel and initiatives, and the ongoing development of coordinated policies between SC and DC. Here I note with some amusement that #114 was raised to the SC board, but the only people who have updated the issue work for DC :).

**Comment by tracykteal** [comment]
Thanks @ctb. To that question about being involved:

- joining a subcommittee is the best way to stay involved in an issue that you care about. Subcommittees generally meet once a month, and have reasonable amounts of email communication, so it's not a big overhead. It is still obviously some time and energy commitment though, but without some level of commitment it is more challenging to stay actively engaged. Each subcommittee does have a [github area](https://github.com/swcarpentry/board/tree/master/subcommittees) so you could add issues there, or email the chair of the committee directly.  
- if you can't join the subcommittee and just want updates, then following the subcommittee reports will give you an overview. Those are distributed in different places across websites, so there could be better clarification about where those goes, and a clear committment to updating those. Data Carpentry's reports are aggregated on our [governance](http://www.datacarpentry.org/governance/) page. 

On issues outside of committees, there isn't this formal structure and conversations happen in a variety of places. Our job and commitment as staff is to keep an eye on those conversations and be engaged and to bring things to our Steering Committees. We do see many ideas for projects emerge and even problems that arise, more than we can take immediate action on, but things aren't dropping off our radar. Like any organization we're working on prioritizing activities, and a key part of that prioritization is interest and engagement from the community. Some of the other things are less exciting and involve things like making sure the servers keep running. What we're not doing is letting people know that we're aware of issues, and have it on a roadmap, or that the Steering Committees are aware of them, but we aren't working on it right now. I think making that clear can help and we can even set some github tags for things that arise in github issues. We are constantly looking at priorities, so if we see things pick up on a issue, we can reprioritize. Ideally we'd have our roadmap and milestones somewhere obvious, and we're working on that too, if we could figure out how to get a good summary out of Asana. 

On your point of bringing issues to staff or Steering Committee members attention directly and in a public forum, we do now have a joint [github carpentries organization](https://github.com/carpentries). We could set up something like a 'suggestion box' there. Is that along the lines of something that would be useful?

**Comment by ctb** [comment]
A suggestion box (with some sort of clearly communicated expectations around response times and engagement, even if it's just "message received!") would be great!

Many open source communities have developed slightly formal methods to handle specific suggestions, e.g. the [Python Enhancement Proposals](https://www.python.org/dev/peps/pep-0001/).  This kind of writeup has the benefit of placing proposals and activities before the entire community in an explicit and well communicated form, and can help avoid the potential problem of siloed activities; it also helps that it places a bit of a burden on people who are passionated about wild-eyed ideas by making them invest time and effort in clear communication & discussion before any significant proposal is adopted.  I see some real value in that kind of explicitness.

I'll close this issue but if people have something to add I welcome it!

**Comment by ctb** [comment]
Whoops, and now I see that #140 was a new issue that covered this same ground - managed to miss that. Sorry @wking.

**Comment by ErinBecker** [comment]
@ctb @wking This is an important discussion and one that goes beyond the question of what specific policies/procedures should be for formalizing interactions between the community and SWC/DC steering committees and subcommittees. To my mind this question should be part of a broader conversation about how we (staff and committee members) facilitate interactions among all members of our community. We'd like to think broadly about this question and invite thoughts and suggestions from community members in helping to shape our overall communication strategy. We've started a new repository [here](https://github.com/carpentries/conversations) to get community input as we move forward in thinking about our strategy. That channel will be monitored by Carpentry staff and will host communications-related decisions as they are developed with the input of the community.
