### ISSUE TITLE
Link on GitHub Science showcase points to deprecated repo

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/board#142]
I stumbled upon this GitHub showcase: https://github.com/showcases/science that lists SWC. However it points to the deprecated bc repository. It might be worth updating it with a link to a more current repository.

**Comment by jduckles** [comment]
Any idea on how we get showcases changed? I can't find anything about how to make or recommend changes 😬.

**Comment by fmichonneau** [comment]
I'm not sure, maybe we'd need to contact GitHub directly?

**Comment by jduckles** [comment]
Ok, I created a meta-repo to act as a target repo for the showcase:

https://github.com/swcarpentry/swcarpentry

**Comment by fmichonneau** [comment]
This looks great!

**Comment by jduckles** [comment]
And GitHub updated it already! https://github.com/showcases/science
