### ISSUE TITLE
Proposed revision for Lesson Maintainer subcommittee

### ISSUE THREAD

**Issue by k8hertweck** [swcarpentry/board#154]
**Proposed Revision for Lesson Maintainer Subcommittee**

This proposal follows the expectations/subheadings outlined in the [subcommittee proposal instructions](https://github.com/swcarpentry/board/blob/master/subcommittees/proposal_instructions.md), and is being submitted in conjunction with a proposal to create a separate Lesson Infrastructure  #subcommittee (#155).

**Current description of lessons subcommittee**: [website](http://software-carpentry.org/join/subcom/maintainers/), [board repo](https://github.com/swcarpentry/board/blob/master/maintainers.md), also related to [old lesson organization committee](https://github.com/swcarpentry/board/tree/master/subcommittees/lessons)

**Specific goals**
Each subcommittee member is expected to maintain their assigned lesson repository

**Steps**

- Review and merge PRs for assigned repo (both content and templates)
- Guide discussions around development and evolution of content for assigned lessons
- Manage issues for assigned repo
- Review communications from Lesson Infrastructure Subcommittee and implement guidelines as recommended

**Timeline**

- Maintenance of assigned repository is ongoing
- Lesson Infrastructure meets quarterly
- Maintainers welcome to attend
- Maintainers receive summary of meeting

**Measuring success**

- Continuation of functional, continually improved lessons
- Increased participation from community in lesson maintenance

**Members**

- http://software-carpentry.org/lessons/ 
- http://www.datacarpentry.org/lessons/  

**Budget**
N/A

**Comment by wking** [comment]
One of the issues with the current/old lesson subcommittee was that it had [no clear responsibilities][1].  It was mostly “sign up for [maintainers@][2] and feel free to comment their or file lesson-template PRs”.  The maintainership of the template and example has also been unclear (swcarpentry/DEPRECATED-lesson-template#262).  I'd recommend making the maintainership of swcarpentry/styles and swcarpentry/lesson-example very clear (with README entries) and then dropping maintainers as a distinct subcommittee.  Maintainers (and anyone else who is interested) can continue to communicate via their repos and maintainers@, and I don't see any purpose to organizing a subcommittee in addition to those channels.

[1]: https://github.com/swcarpentry/board/issues/19#issuecomment-77645964
[2]: http://lists.software-carpentry.org/listinfo/maintainers

**Comment by k8hertweck** [comment]
I think we've made great strides over the last few months in determining what exactly a subcommittee/task force should be, and making sure their objectives are clearly described (although the latter is always a work in progress!). I hope we'll be able to resolve the issues you mention about the general repos with the lesson infrastructure subcommittee. 

It does seem necessary to have a designated set of roles and responsibilities for what a maintainer actually does (which we currently do), as well as a set of standard operating procedures (not as clear right now). Therefore, I would argue that it is important to have a collective description for the maintainers that at least somewhat parallels the other "working groups" we have, and that a subcommittee is the best descriptor at this point in time. As someone who was tapped to lead this group several months back, it's still not clear to me how all of these moving pieces (lesson changes, releases, personal preferences of interactivity among maintainers, etc) are coordinated, so I can't imagine what it's like for newcomers trying to acclimate or considering joining the group. Hopefully, organization of maintainers as a subcommittee will make the process more manageable.

**Comment by wking** [comment]
On Tue, Dec 20, 2016 at 06:12:11PM -0800, Kate Hertweck wrote:
> … as well as a set of standard operating procedures (not as clear
> right now)…

I've tried to get docs for “care and feeding of your lesson” included
with the template repo (swcarpentry/DEPRECATED-lesson-template#124,
swcarpentry/DEPRECATED-lesson-template#215).  With the deprecation of
lesson-template, I'd like to see docs with these SOPs landing under
swcarpentry/styles doc/.  This would both make it easy to keep the
docs in sync with the template repo, and make it clear that the
template maintainers were responsible for providing docs.

But if that continues to be not the consensus approach, then keeping
docs somewhere else makes sense.  And a subcommittee directory seems
like a resonable place for that (although you'd want to be very clear
about how you expect the subcommittee to interact with the
template-repo maintainers if they weren't two hats for the same set of
people).

**Comment by rgaiacs** [comment]
Approved as [Motion #2017-01-04/3](https://github.com/swcarpentry/board/blob/master/minutes/minutes-2017-01-04.md#motion-2017-01-043).
