### ISSUE TITLE
Back up Jupyter's Openness, Diversity and Dignity statement 

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/board#169]
Jupyter project published on their website https://blog.jupyter.org/2017/01/31/openness-diversity-and-dignity/. Their announcement goes on the same line as our discussion at https://github.com/swcarpentry/website/pull/646.

@JasonJWilliamsNY Can we publish on our website a post of support?

**Comment by wking** [comment]
On Tue, Jan 31, 2017 at 02:03:58AM -0800, Raniere Silva wrote:
> Jupyter project published on their website
> https://blog.jupyter.org/2017/01/31/openness-diversity-and-dignity/.

I don't see how we could have any problems with a post that reiterates
our support for openness, diversity, dignity, non-discrimination,
etc., highlighting our global instructor and workshop base, and making
it clear that we intend to continue pushing for a globalized Carpentry
community in the future.  You don't have to explicitly push back
against a particular government action to make that point.

**Comment by JasonJWilliamsNY** [comment]
@rgaiacs discussion is now in progress on board email thread

**Comment by k8hertweck** [comment]
Since we've blogged about this, is it alright to close this issue?

**Comment by mkuzak** [comment]
agree that's solved, @rgaiacs please close if you agree
