### ISSUE TITLE
Permanent list of standing subcommittees / working groups

### ISSUE THREAD

**Issue by wking** [swcarpentry/board#18]
Yesterday @katyhuff [posted a plan for subcommittees][1] on the blog.  While it's good to use the blog to get the word out, I'd prefer a permanent list of such groups to live somewhere that's actively maintained.  We do post blog edits from time to time, but mostly it's write-once there.  Personally, I'd like to see this be either a board.software-carpentry.org site (I like the old “board” more than the current “steering committee” ;) with it's own repository (e.g. this one ;) or a software-carpentry.org/steering-committee/ subsite managed under swcarpentry/site, since we likely want to publish more information about the board than a list of working groups, and just pointing folks at this repository isn't very polished (especially when GitHub makes hosting a Jekyll powered site is so easy ;).

[1]: http://software-carpentry.org/blog/2015/03/scf-subcommittees.html

**Comment by katyhuff** [comment]
> I'd prefer a permanent list of such groups to live somewhere that's actively maintained. 

We have one in a private repository in the board repo. 

>  (I like the old “board” more than the current “steering committee” ;)

I'm not sure what you mean by this. Do you mean you preferred the people on the interim steering committee more than you like the current steering committee members? 

If so, I find that confusing, having been on both and somewhat upsetting, having spent a lot of time working hard on the latter. In any case, "board" and "steering committee" are one and the same - see my other comment about numfocus, namechanges, the word "board", and namechanges causing confusion.


>  with it's own repository (e.g. this one ;) 

This is, and has been, the public repository for the Steering Committee. We have been publishing our minutes here, decisions we make, etc. 

> a software-carpentry.org/steering-committee/ subsite managed under swcarpentry/site,

Like this: http://software-carpentry.org/scf/index.html ?

**Comment by katyhuff** [comment]
(note that the minutes from the last few meetings will appear here soon as they have been in the past. There have been transitional delays, but they will, in the future, appear here less than two weeks after each meeting we have.)

**Comment by wking** [comment]
On Fri, Mar 06, 2015 at 12:58:07PM -0800, Katy Huff wrote:
> > I'd prefer a permanent list of such groups to live somewhere
> > that's actively maintained.
>
> We have one in a private repository in the board repo.

So this was a one-off request for members, and futher updates to the
advisor panels will be via personal invite?

> > (I like the old “board” more than the current “steering committee” ;)
>
> I'm not sure what you mean by this. Do you mean you preferred the
> people on the interim steering committee more than you like the
> current steering committee members?

No, I like all the members :).  I just think “steering committee” is a
mouthful, and I didn't realize “board” was off-limits [1].

> If so, I find that confusing, having been on both and somewhat
> upsetting…

Absolutely, and I'm sorry I wasn't more clear.  To be clear, I think
you are all doing great work, and all of my suggestions are just my
thoughts on improving our workflow (and everything has room for
improvement).  For example, I can work on improving my wording ;).

> > a software-carpentry.org/steering-committee/ subsite managed under
> > swcarpentry/site,
>
> Like this: http://software-carpentry.org/scf/index.html ?

Aha, that is exactly what I wanted :).  I just missed the link because
I thought “Software Carpentry Foundation” would be about the
foundation itself, and not our internal government structure.  Thanks
for clearing me up.

So my issue here is now:

* Do we want to list standing subcommittees under
  software-carpentry.org/scf/?  Or keep the list in the private board
  repository?

I think that depends on the planned models for:

* Filling the non-committee member slots going forward.
* Publishing the discussion / logs of sub-committee activity.

[1]: https://github.com/swcarpentry/board/issues/17#issuecomment-77633293

**Comment by jiffyclub** [comment]
It might be a good idea to add the subcommittee descriptions to software-carpentry.org/scf/ at some point (mostly so we can recognize the people volunteering for the subcommittees). But honestly at this point I don't even know how to describe my subcommittee. I don't think it's desperately important that we make a public list, though, since these are internal advisory groups (brain trusts?) and since we won't be doing ongoing public recruitment to these groups.

**Comment by katyhuff** [comment]
Sorry, I butterfingered this. Didn't mean to close it. I do agree with @jiffyclub . When new members are needed for subcommittees, I do expect that it will come from : 

1) people who have expressed interest
2) and responses to more calls for additional members on the blog, which I imagine we'll send out whenever we need more folks.

To close this issue, I'm happy to move the list of subcommittees out of the private repos and into this repo. It will look suspiciously similar to the blog post. Will that close this?

**Comment by wking** [comment]
On Fri, Mar 06, 2015 at 02:42:09PM -0800, Katy Huff wrote:
> To close this issue, I'm happy to move the list of subcommittees out
> of the private repo and into this repo. It will look suspiciously
> similar to the blog post. Will that close this?

Absolutely.  I'd consider adding a link from
software-carpentry.org/scf/ to the list, and with my revised
understanding of their informality, I think linking into this GitHub
repository would be the appropriate level of polish.

Thanks for the extremely prompt response to this issue, and the
related ones spun off by the blog post :).

**Comment by karinlag** [comment]
On 06/03/15 23:42, Katy Huff wrote:
> Sorry, I butterfingered this. Didn't mean to close it. I do agree with
> @jiffyclub <https://github.com/jiffyclub> . When new members are needed
> for subcommittees, I do expect that it will come from :
>
> 1) people who have expressed interest
> 2) and responses to more calls for additional members on the blog, which
> I imagine we'll send out whenever we need more folks.
 >
> To close this issue, I'm happy to move the list of subcommittees out of
> the private repos and into this repo. It will look suspiciously similar
> to the blog post. Will that close this?

I am very for the subcomittee list (with people) being very visible 
somewhere. I personally want them to be visible so that people can see 
who is contributing and also that, if people feel like they want to do 
more, they know there is an option to do so. Each committee in itself 
might be full at the time, but that is another matter.

K

**Comment by katyhuff** [comment]
@karinlag great! This was completed in PR #10!

**Comment by wking** [comment]
On Sun, Mar 08, 2015 at 09:32:04PM -0700, Katy Huff wrote:
> This was completed in PR #10! 

Public standing subcommittees were PR #21.  #10 is an issue about
voting rules ;).

**Comment by katyhuff** [comment]
whoops. you're right!
