### ISSUE TITLE
Revise minutes for Trainers meeting

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/board#190]
In the minutes [here](https://github.com/swcarpentry/board/blob/c20cad24d638da1f69c43b6c96be45786778773b/subcommittees/trainers/minutes/2017-03-23-business.md) there is the quote "Moving forward, we will continue this process four times a year so that we always have a plan three months out. For non-summer months, the goal will be to offer 1 time zone per month." This should actually say "offer 1 **per** time zone per month."

This means a total of 6 per month (4 US time zones plus Europe + Auz/NZ). Could someone please update these minutes?

@ChristinaLK @raynamharris @karinlag

**Comment by raynamharris** [comment]
Done.

**Comment by ErinBecker** [comment]
Thanks @raynamharris!
