### ISSUE TITLE
governance-related docs not in governance directory 

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/board#205]
To clean up this repo, I would like to move these documents to the subdirectory called governance. Would that create any new problems?

- advisory-council.md
- executive-director.md
- governance.md
- issue-escalation.md
- membership.md
- mission-statement.md
- motion-of-no-confidence.md
- proxy-membership.md
- pursuit-of-funding.md
- steering-committee-chair.md
- strategy/strategic_plan.md

**Comment by jduckles** [comment]
There are some inbound links to some of these from `swcarpentry/website` so we should just `grep` for those and change them to the new location when the move happens.

**Comment by raynamharris** [comment]
I'll leave them as they are.
