### ISSUE TITLE
mentoring repo

### ISSUE THREAD

**Issue by ChristinaLK** [swcarpentry/board#231]
with the move of carpentrycon + trainers to the carpentries org + their own repos, should mentoring do the same?  if yes, I can coordinate w/ Jamie + Marian for that transition.

**Comment by mkuzak** [comment]
Yes, I agree, mentoring should move to carpentries organisation.

**Comment by mkuzak** [comment]
Looks like there is [carpentries/mentoring](https://github.com/carpentries/mentoring) repository.
@ErinBecker can we migrate mentoring here?

**Comment by raynamharris** [comment]
Yes, @mkuzak There is an exciting repo that Kate and I started over a year ago. Please migrate the mentoring committee things there. 

Also, the existing 'subcommittee.md' file only contains a few links. This document will be irrelevant once you migrate your documents, so it can be deleted.

**Comment by ChristinaLK** [comment]
Can we delete the mentoring folder from this repo?

**Comment by ErinBecker** [comment]
@ChristinaLK - yes please. It's very confusing to have two duplicate locations of these files.

**Comment by mkuzak** [comment]
we're already workinig in the new carpentries repo
don't see anything in the way of deleting the one in swc organisation

**Comment by ChristinaLK** [comment]
I'll submit a PR.
