### ISSUE TITLE
Steering committee elections

### ISSUE THREAD

**Issue by wking** [swcarpentry/board#3]
I see from today's morning meeting notes that the election process is still being worked out.  To avoid runoffs and the like, [Gentoo uses][1] a [Condorcet][2] flavor (the [Shulze method][3]), and [a number of other organizations do too][4].  This has the advantage of folks not having to game the system by avoiding voting for candidates they thing are unlikely to win.  It also allows folks to express preferences for multiple candidates they like, since you're ranking all the cantidates instead of just voting for one.

[1]: https://www.gentoo.org/proj/en/elections/index.xml#doc_chap4_sect4
[2]: http://en.wikipedia.org/wiki/Condorcet_method
[3]: http://en.wikipedia.org/wiki/Schulze_method
[4]: http://en.wikipedia.org/wiki/Condorcet_method#Use_of_Condorcet_voting

**Comment by wking** [comment]
With the first elections three weeks away [1], we should probably be
settling on election rules in the next week and tooling within two
weeks so we can start spreading the word about how this is going to
work a week before we actually kick this off ;).  I think @gvwilson is
starting to think about the tooling behind vote collection [2], but I
think this issue is as far as we've gotten on the election method.

[1]: http://software-carpentry.org/blog/2014/12/election-date.html
[2]: http://software-carpentry.org/blog/2014/12/minutes-2014-dec-02.html
     GW: investigate online voting system used by Python Software Foundation

**Comment by gvwilson** [comment]
The board is working on it.

**Comment by wking** [comment]
On Sun, Jan 04, 2015 at 07:55:28PM -0800, Greg Wilson wrote:
> The board is working on it.

I don't see details on any discussions in the board minutes, but we
got some details at the 2015-01-22 lab meeting [1]:

> ElectionBuddy
>   Monday: you'll get an email with a link.
>   You have 7 votes (1 per seat on the steering committee)
>   Tallied at the end of the week (friday of next week)
>   plurality vote, extra member if there is a tie
>   returning officer will see votes, but not who made the votes
>   Check your spam folders!

It looks like we're using electionbuddy [2].  I'm curious about the
rationale behind the election process, since plurality-at-large voting
favors slates of candidates and not the proportional representation
you get out of transferable vote systems [3].  With a population as
diverse as SWC, I'd prefer a voting system geared towards proportional
representation.

[1]: https://etherpad.mozilla.org/swc-labmeeting-2015-01
[2]: http://electionbuddy.com/
[3]: http://en.wikipedia.org/wiki/Plurality-at-large_voting

**Comment by katyhuff** [comment]
I'm going to go ahead and mark this as closed, since the lab meeting cleared up the need for details and the election is now over. Before the next election, we can reopen this discussion.

**Comment by wking** [comment]
On Mon, Mar 09, 2015 at 12:13:49PM -0700, Katy Huff wrote:
> Before the next election, we can reopen this discussion.

I'd recommend a ‘deferred’ label for things like this, so we can look
through the deferred issues periodically to keep them from being
forgotten.  I don't mind if we leave things like this opened or
closed, so long as there is a way to separate “this is no longer an
issue” from “this isn't an issue we have to deal with in the next six
months”.  I can create the label and apply it to my issues if that
sounds reasonable.
