### ISSUE TITLE
Falling behind on steering committee minutes?

### ISSUE THREAD

**Issue by wking** [swcarpentry/board#42]
GitHub just emailed me about #41, where @r-gaia-cs catches us up on mentoring activity to within two weeks of the present.  But looking in `minutes/` it looks like we're exactly three months stale on steering committee minutes, and I don't see any PRs pushing new material.  What's everyone up to?  Is there any tooling work I can do that would help make recording/publishing minutes more painless?

**Comment by katyhuff** [comment]
You're quite right @wking . We'll check in with @karinlag to see what snags are slowing our secretarial process.

**Comment by r-gaia-cs** [comment]
> But looking in minutes/ it looks like we're exactly three months stale on steering committee minutes, and I don't see any PRs pushing new material.  What's everyone up to?

Sorry for us being slowly to make the minutes public.

>  Is there any tooling work I can do that would help make recording/publishing minutes more painless?

Thanks for the offer. I think that is just that everyone are busy at this part of the year. I will help @karinlag with any problem related to Git.

**Comment by karinlag** [comment]
Added the latest last week, closing.
