### ISSUE TITLE
Give credit to former members of subcommittee

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/board#61]
Suggestions to how manage former members at https://github.com/swcarpentry/board/blob/master/subcommittees/subcommittees.md?

**Comment by karinlag** [comment]
On 10/24/2015 11:17 PM, Raniere Silva wrote:
> Suggestions to how manage former members at
> https://github.com/swcarpentry/board/blob/master/subcommittees/subcommittees.md?


...how about a "Former members" section at the end, divided by committee?

K

**Comment by apawlik** [comment]
+1
In the UK sometimes the term "Alumni" is called but not being a native English speaker I don't have a very good sense for the appropriateness of this word in this context.

Training Leader
The Software Sustainability Institute, University of Manchester
w: www.software.ac.uk
t: @aleksandrana | @SoftwareSaved
