### ISSUE TITLE
Define date for second round of pre-workshop help session 

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/board#70]
@k8hertweck Could you provide me with the date for the second try of the pre-workshop help session?

**Comment by k8hertweck** [comment]
I'm aiming for Wednesday, Jan 20, 10:00 EST and 19:00 EST (time slots to match the debriefing sessions). I'll email around the mentoring committee and get a list of upcoming instructors.

**Comment by rgaiacs** [comment]
- [X] Add date to calendar.
- [X] Send email address to @k8hertweck.
- [ ] Clean etherpads: http://pad.software-carpentry.org/pre-workshop-morning and http://pad.software-carpentry.org/pre-workshop-evening.
- [ ] Send email to instructors.
- [ ] Send email to discuss list.

@k8hertweck Could you do the last three items from the list above? And close this issue. Thanks.
