### ISSUE TITLE
Loss-of-confidence steering committe elections

### ISSUE THREAD

**Issue by wking** [swcarpentry/board#9]
The steering committee has [responsibilities][1], but there's no recourse if they don't meet their responsibilities.  For example, what happens when a member doesn't attend 75% of the year's meetings?  I [discussed][2] [this][3] [with][4]  @katyhuff in #5, and my current feeling is that relying on the honor system is probably fine (we're likely to elect dedicated committee members), but that it would be nice to have procedures in place for loss-of-confidence re-elections.

My [earlier summary][2] of [Gentoo's rules][5] was incorrect.  They specify both full-council elections (when a given meeting has <50% attendance), and single-member elections (when a single member is a slacker).  Single-member elections are for a reduced term (to keep the full elections in sync), but full-council elections reset the term (to avoid excessive election density ;).

Personally, I'd say either a 50% vote by the committee or a petition signed by over half the broader voting constituency should be enough to force an early election.  I don't see the point of having separate rules for a single-position election, so I'd just go with the full-committee, term-resetting election within a month after the committee vote or petition submission.  Folks could always re-elect the committee members that they thought were doing a good job.

[1]: https://github.com/swcarpentry/board/blob/dc8afac323ebdc6df6d2da033e955e89014a7121/committee-roles.md#responsibilities
[2]: https://github.com/swcarpentry/board/pull/5#issuecomment-69405685
[3]: https://github.com/swcarpentry/board/pull/5#issuecomment-69406360
[4]: https://github.com/swcarpentry/board/pull/5#issuecomment-69407414
[5]: http://wiki.gentoo.org/wiki/GLEP:39#Specification

**Comment by katyhuff** [comment]
Hi Trevor. Can you submit a pull request describing your proposed policy in its own markdown file? Perhaps call it "loss-of-confidence.md"? This will make it easier for the SCF SC to discuss and vote on this concern.

**Comment by katyhuff** [comment]
Thank you for submitting a pull request for this. The Steering Committee would like to take some time to review your pull request and consider the implications. We will make comments on #24 accordingly.
